### ISSUE TITLE
Paths not loaded for all summaries on devices

### ISSUE THREAD

**Issue by kennybuddy** [koledecou/TrailBook#2]
Kole - Attached is the path issue we reviewed on Friday, pls fix -

03-01 13:03:12.273    1598-1759/com.trailbook.kole E/dalvikvm﹕ Could not find class 'javax.management.ObjectName', referenced from method com.mongodb.util.management.jmx.JMXMBeanServer.createObjectName
03-01 13:03:14.315    1598-1783/com.trailbook.kole E/File﹕ fail readDirectory() errno=2
03-01 13:03:14.435    1598-1786/com.trailbook.kole E/File﹕ fail readDirectory() errno=2
03-01 13:03:15.947    1598-1780/com.trailbook.kole E/BufferQueue﹕ [unnamed-1598-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=2 undequeudCount=1)
03-01 13:03:15.947    1598-1780/com.trailbook.kole E/BufferQueue﹕ [unnamed-1598-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=2 undequeudCount=1)
03-01 13:03:15.947    1598-1780/com.trailbook.kole E/BufferQueue﹕ [unnamed-1598-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=2 undequeudCount=1)
03-01 13:03:16.607    1598-1780/com.trailbook.kole E/BufferQueue﹕ [unnamed-1598-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=2 undequeudCount=1)
03-01 13:03:16.607    1598-1780/com.trailbook.kole E/BufferQueue﹕ [unnamed-1598-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=2 undequeudCount=1)
03-01 13:03:16.607    1598-1780/com.trailbook.kole E/BufferQueue﹕ [unnamed-1598-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=2 undequeudCount=1)
03-01 13:03:17.478    1598-1780/com.trailbook.kole E/BufferQueue﹕ [unnamed-1598-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=2 undequeudCount=1)
03-01 13:03:17.478    1598-1780/com.trailbook.kole E/BufferQueue﹕ [unnamed-1598-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=2 undequeudCount=1)
03-01 13:03:17.478    1598-1780/com.trailbook.kole E/BufferQueue﹕ [unnamed-1598-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=2 undequeudCount=1)
03-01 13:03:17.478    1598-1780/com.trailbook.kole E/BufferQueue﹕ [unnamed-1598-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=2 undequeudCount=1)
03-01 13:03:17.478    1598-1780/com.trailbook.kole E/BufferQueue﹕ [unnamed-1598-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=2 undequeudCount=1)
03-01 13:03:17.478    1598-1780/com.trailbook.kole E/BufferQueue﹕ [unnamed-1598-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=2 undequeudCount=1)
03-01 13:03:17.478    1598-1780/com.trailbook.kole E/BufferQueue﹕ [unnamed-1598-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=2 undequeudCount=1)
03-01 13:03:17.488    1598-1780/com.trailbook.kole E/BufferQueue﹕ [unnamed-1598-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=2 undequeudCount=1)
03-01 13:03:17.618    1598-1780/com.trailbook.kole E/BufferQueue﹕ [unnamed-1598-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=2 undequeudCount=1)
03-01 13:03:17.618    1598-1780/com.trailbook.kole E/BufferQueue﹕ [unnamed-1598-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=2 undequeudCount=1)
03-01 13:03:17.618    1598-1780/com.trailbook.kole E/BufferQueue﹕ [unnamed-1598-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=2 undequeudCount=1)
03-01 13:03:17.618    1598-1780/com.trailbook.kole E/BufferQueue﹕ [unnamed-1598-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=2 undequeudCount=1)
03-01 13:03:17.628    1598-1780/com.trailbook.kole E/BufferQueue﹕ [unnamed-1598-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=2 undequeudCount=1)
03-01 13:03:17.628    1598-1780/com.trailbook.kole E/BufferQueue﹕ [unnamed-1598-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=2 undequeudCount=1)
03-01 13:03:17.628    1598-1780/com.trailbook.kole E/BufferQueue﹕ [unnamed-1598-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=2 undequeudCount=1)

**Comment by koledecou** [comment]
fixed (included stack trace about BufferQueue unrelated to issue).  that has something to do with google maps (no network available?)
